name: Build xray-core feed

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: write

env:
  PACKAGE_NAME: xray-core
  FEED_NAME: xray_core
  OPENWRT_MAJOR: "24.10"
  OPENWRT_VERSION: "24.10.5"

jobs:
  build:
    name: Build packages for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          - arch: aarch64_cortex-a53
            runtime_test: false
#          - arch: aarch64_cortex-a72
#            runtime_test: false
#          - arch: aarch64_cortex-a76
#            runtime_test: false
#          - arch: aarch64_generic
#            runtime_test: true
#          - arch: arm_arm1176jzf-s_vfp
#            runtime_test: false
#          - arch: arm_arm926ej-s
#            runtime_test: false
#          - arch: arm_cortex-a15_neon-vfpv4
#            runtime_test: true
#          - arch: arm_cortex-a5_vfpv4
#            runtime_test: false
#          - arch: arm_cortex-a7
#            runtime_test: false
#          - arch: arm_cortex-a7_neon-vfpv4
#            runtime_test: false
#          - arch: arm_cortex-a8_vfpv3
#            runtime_test: false
#          - arch: arm_cortex-a9
#            runtime_test: false
#          - arch: arm_cortex-a9_neon
#            runtime_test: false
#          - arch: arm_cortex-a9_vfpv3-d16
#            runtime_test: false
#          - arch: arm_fa526
#            runtime_test: false
#          - arch: arm_xscale
#            runtime_test: false
#          - arch: i386_pentium-mmx
#            runtime_test: true
#          - arch: i386_pentium4
#            runtime_test: false
#          - arch: loongarch64_generic
#            runtime_test: false
#          - arch: mips64_mips64r2
#            runtime_test: false
#          - arch: mips64_octeonplus
#            runtime_test: false
#          - arch: mips64el_mips64r2
#            runtime_test: false
#          - arch: mips_24kc
#            runtime_test: true
#          - arch: mips_4kec
#            runtime_test: false
#          - arch: mips_mips32
#            runtime_test: false
#          - arch: mipsel_24kc
#            runtime_test: false
#          - arch: mipsel_24kc_24kf
#            runtime_test: false
#          - arch: mipsel_74kc
#            runtime_test: false
#          - arch: mipsel_mips32
#            runtime_test: false
#          - arch: riscv64_riscv64
#            runtime_test: false
#          - arch: x86_64
#            runtime_test: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@v10
        env:
          ARCH: ${{ matrix.arch }}-openwrt-${{ env.OPENWRT_MAJOR }}
          FEEDNAME: ${{ env.FEED_NAME }}
          PACKAGES: ${{ env.PACKAGE_NAME }}
          NO_REFRESH_CHECK: 1
          INDEX: 1
          KEY_BUILD: ${{ secrets.USIGN_KEY }}
          V: s

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout ${{ env.OPENWRT_VERSION }}
          git pull
          cp ./bin/packages/${{ matrix.arch }}/xray_core/* . || true
          git add Packages
          git add Packages.*
          git add *.ipk
          git commit -m "Add xray_core binary via workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          branch: ${{ env.OPENWRT_VERSION }}

      - name: Store packages
        uses: actions/upload-artifact@v6
        if: github.event_name != 'release'
        with:
          name: ${{ matrix.arch }}-${{ github.sha }}-packages
          path: |
            Packages
            Packages.*
            *.ipk

      - name: Store logs
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.arch }}-${{ github.sha }}-logs
          path: logs/

      - name: Remove logs and other
        run: |
          sudo rm -rf ./logs/ || true
          sudo rm -rf ./bin/ || true
